# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from cape.connector.proto import (
    data_connector_pb2 as cape_dot_connector_dot_proto_dot_data__connector__pb2,
)


class DataConnectorStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_stream(
            "/cape.DataConnector/Query",
            request_serializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.QueryRequest.SerializeToString,
            response_deserializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.Record.FromString,
        )
        self.Schema = channel.unary_unary(
            "/cape.DataConnector/Schema",
            request_serializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.SchemaRequest.SerializeToString,
            response_deserializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.SchemaResponse.FromString,
        )
        self.Version = channel.unary_unary(
            "/cape.DataConnector/Version",
            request_serializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.VersionRequest.SerializeToString,
            response_deserializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.VersionResponse.FromString,
        )


class DataConnectorServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Schema(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Version(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DataConnectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Query": grpc.unary_stream_rpc_method_handler(
            servicer.Query,
            request_deserializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.QueryRequest.FromString,
            response_serializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.Record.SerializeToString,
        ),
        "Schema": grpc.unary_unary_rpc_method_handler(
            servicer.Schema,
            request_deserializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.SchemaRequest.FromString,
            response_serializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.SchemaResponse.SerializeToString,
        ),
        "Version": grpc.unary_unary_rpc_method_handler(
            servicer.Version,
            request_deserializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.VersionRequest.FromString,
            response_serializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.VersionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "cape.DataConnector", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class DataConnector(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Query(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/cape.DataConnector/Query",
            cape_dot_connector_dot_proto_dot_data__connector__pb2.QueryRequest.SerializeToString,
            cape_dot_connector_dot_proto_dot_data__connector__pb2.Record.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Schema(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cape.DataConnector/Schema",
            cape_dot_connector_dot_proto_dot_data__connector__pb2.SchemaRequest.SerializeToString,
            cape_dot_connector_dot_proto_dot_data__connector__pb2.SchemaResponse.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Version(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cape.DataConnector/Version",
            cape_dot_connector_dot_proto_dot_data__connector__pb2.VersionRequest.SerializeToString,
            cape_dot_connector_dot_proto_dot_data__connector__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
