# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from cape.connector.proto import (
    data_connector_pb2 as cape_dot_connector_dot_proto_dot_data__connector__pb2,
)


class DataConnectorStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

    Args:
      channel: A grpc.Channel.
    """
        self.Query = channel.unary_stream(
            "/cape.DataConnector/Query",
            request_serializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.QueryRequest.SerializeToString,
            response_deserializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.Record.FromString,
        )
        self.Version = channel.unary_unary(
            "/cape.DataConnector/Version",
            request_serializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.VersionRequest.SerializeToString,
            response_deserializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.VersionResponse.FromString,
        )


class DataConnectorServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Query(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Version(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DataConnectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Query": grpc.unary_stream_rpc_method_handler(
            servicer.Query,
            request_deserializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.QueryRequest.FromString,
            response_serializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.Record.SerializeToString,
        ),
        "Version": grpc.unary_unary_rpc_method_handler(
            servicer.Version,
            request_deserializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.VersionRequest.FromString,
            response_serializer=cape_dot_connector_dot_proto_dot_data__connector__pb2.VersionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "cape.DataConnector", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
