name: Main
on: [push]
jobs:
  build:
    name: Examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
    steps:
      - name: Setup python ${{ matrix.python-version }} Environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run Make Examples
        run: |
          make bootstrap
          make examples